# name: CI/CD Pipeline

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4

#     - name: Set up Docker
#       uses: docker/setup-buildx-action@v3

#     - name: Build Docker image
#       uses: docker/build-push-action@v5
#       with:
#         context: .
#         file: ./Dockerfile
#         push: false
#         load: true

#     - name: Run Docker Compose
#       run: docker compose up -d --build

name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Pull CentOS 7 Image
      run: docker pull centos:7

    - name: Install Docker Compose on CentOS 7
      run: |
        docker run -d --name centos7 centos:7
        docker exec centos7 yum update -y
        docker exec centos7 yum install -y epel-release
        docker exec centos7 yum install -y python3-pip
        docker exec centos7 pip3 install docker-compose

    - name: Run Docker Compose
      run: |
        docker cp . centos7:/workspace
        docker exec -w /workspace centos7 docker-compose up -d --build
